name: OATS Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/oats-tests.yml
      - mise.toml
      - .mise/tasks/oats-tests.sh
      - 'logging-k8s-stdout-otlp-json/**'
      - 'javaagent-declarative-configuration/**'
      - 'spring-declarative-configuration/**'
      - 'doc-snippets/extensions-minimal/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  acceptance-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 17

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

      - name: Run OATS tests
        run: mise run oats-tests
