name: OATS Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/oats-tests.yml
      - mise.toml
      - .mise/tasks/oats-tests.sh
      - 'logging-k8s-stdout-otlp-json/**'
      - 'javaagent-declarative-configuration/**'
      - 'doc-snippets/extensions-minimal/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  acceptance-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1

      - name: Run OATS tests
        run: mise run oats-tests
