version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: extensions-full/oats/Dockerfile
    environment:
      OTEL_SERVICE_NAME: "extensions-full-test-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4318
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://lgtm:4318/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      # Set APP_VERSION for TestResourceProvider
      APP_VERSION: "1.0.0-test"
    ports:
      - "8080:8080"